### ISSUE TITLE
An error has occurred

### ISSUE THREAD

**Issue by Duxedraft** [celian-rib/vscode-webvalidation-extension#19]
The extension fails to validate code and instead displays "An error has occurred". I've tried to disable, uninstall, re-install but nothing seems to work.

**Comment by celian-rib** [comment]
Hi @Duxedraft thanks for reporting this issue !
Could you provide more information on it ?

For example : 
- what version of vscode are you working with ?
- were you working offline ? (The extension does not work offline).
- Is the issue still happening ? (It may be due to the W3C API being down).

On my side, I will note that the error messages are not great and have to be improved.
Thanks :)

**Comment by Duxedraft** [comment]
Hey @celian-rib. Thanks for your quick response. To answer your questions, I'm using Visual Studios Version: 1.61.0, not working offline and the issue is still happening.

Thanks for looking into it!

**Comment by celian-rib** [comment]
Hey @Duxedraft i'm currently working on improving the error handling of the extension.
Meanwhile, if you have time, is it possible for you to :
- open vscode

- toggle the dev tool:
![Screenshot 2021-10-09 at 18 47 32](https://user-images.githubusercontent.com/38594012/136667226-c93f4d6a-9a4d-4b11-88d3-eeffe4830f1b.png)

- select the console tab: 
![Screenshot 2021-10-09 at 18 50 09](https://user-images.githubusercontent.com/38594012/136667279-1b4cc0fa-d683-4b8a-bf4e-c309a43ac1db.png)

- start the W3C validation with the extension on a CSS or HTML file:
![image](https://user-images.githubusercontent.com/38594012/136667370-28aaa04d-1c90-4e77-a42a-3e2caeccddc8.png)

- and then send me the **full logs from the console tab** (A screenshot of the error is enough)!

That would be awesome if you could do that!
I think your issue is also related to #13 , so that would be even greater if I find the cause.

Thank you, have a nice day!

**Comment by Duxedraft** [comment]
Hey @celian-rib 

Below is a screenshot of the log. Something about a certificate (not sure whether it's from the extension or my end) I reckon? Let me know if theres anything else I can help you with. Cheers!

<img width="540" alt="image" src="https://user-images.githubusercontent.com/92181338/136667853-088a92a0-670f-4dd9-8b5a-c4d312f3a861.png">

**Comment by celian-rib** [comment]
Thank you for responding so quickly ! Can you extend the messages from the console ?
![image](https://user-images.githubusercontent.com/38594012/136667965-54887971-5c9f-47df-bf85-6750cfb2abb0.png)
![image](https://user-images.githubusercontent.com/38594012/136667967-41c19f63-e9cc-45ab-9f37-9b4de0cf15cc.png)

(By clicking on the grey arrow)
Thanks 👍🏻

**Comment by Duxedraft** [comment]
No worries @celian-rib... here you go!
<img width="540" alt="image" src="https://user-images.githubusercontent.com/92181338/136668171-43e975d9-73ba-4bcc-a034-6153ec9ead55.png">

**Comment by celian-rib** [comment]
Hey @Duxedraft , I have released a new update with a **possible** fix of the issue.
It is available and the extension should update just after you open vscode.

I hope it will fix the issue, keep me updated, thanks !

**Comment by Duxedraft** [comment]
Hey @celian-rib, I made the update but the error is still there. Maybe the problem is on my end. I'll look into it. Thanks for troubleshooting as well

**Comment by celian-rib** [comment]
Hi @Duxedraft, im sorry to hear that.
I think your issue impacted by the recent certificates expiration (September 2021) https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ 

So I guess the issue is coming from your side, this may happen because you have an out of date certificate on your machine.
Thanks and have a nice day!
